FROM node:8
RUN groupadd -g 1100 nodegroup
RUN useradd -u 1500 nodeuser
RUN usermod -a -G nodegroup nodeuser
ADD yarn.lock /yarn.lock
ADD package.json /package.json
ENV NODE_PATH=/node_modules
ENV PATH=$PATH:/node_modules/.bin
RUN yarn
USER root
RUN chown -R 1100:nodegroup /tmp
WORKDIR /tmp
USER 1110
ADD --chown=1100:nodegroup . /tmp
EXPOSE 3000
EXPOSE 35729
ENTRYPOINT ["/bin/bash", "/tmp/run.sh"]
CMD ["start"]
