FROM node:10-alpine

RUN mkdir -p /tmp/node_modules && chown -R 1100:node /tmp

WORKDIR /tmp

COPY package*.json ./

RUN npm install
USER 1100
COPY --chown=1100:node . .

EXPOSE 8080
CMD npm run start
