FROM node:8
RUN mkdir -p /tmp/node_modules && chown -R 1100:node /tmp
WORKDIR /tmp
ADD yarn.lock ./
ADD package.json ./
ENV NODE_PATH=/tmp/node_modules
ENV PATH=$PATH:/tmp/node_modules/.bin
RUN yarn
WORKDIR /tmp
RUN chown -R 1100:node /tmp/node_modules/*
RUN useradd -ms /bin/bash 1100
USER 1100
COPY --chown=1100:node . /tmp
RUN chmod 765 /tmp/yarn.lock /tmp/run.sh /tmp/package.json
RUN ls -lrt
RUN pwd
EXPOSE 3000
CMD sh -c "cd /tmp && yarn run start"
